USE sakila;

# List the number of films per category.

SELECT c.category_id, COUNT(f.film_id) as film_number
FROM film_category AS c
LEFT JOIN film AS f
ON c.film_id = f.film_id
GROUP BY category_id
ORDER BY film_number DESC;

# using just group by 

SELECT category_id, COUNT(film_id) as film_number
FROM film_category
GROUP BY category_id
ORDER BY film_number DESC;


# Retrieve the store ID, city, and country for each store.

SELECT s.store_id, c.city_id, c.city
FROM store AS s
JOIN city AS c
ON  c.city_id
JOIN country AS co
ON c.country_id = co.country_id;


# Calculate the total revenue generated by each store in dollars.

SELECT s.store_id, SUM(p.amount) as total_revenue
FROM payment AS p
JOIN staff AS s
ON  p.staff_id = s.staff_id 
JOIN store AS st 
ON st.store_id = s.store_id
GROUP BY store_id;

# Determine the average running time of films for each category.

SELECT c.category_id, AVG(f.length) AS avg_running_time
FROM film AS f
JOIN film_category AS c
ON c.film_id = f.film_id
GROUP BY c.category_id;

# Identify the film categories with the longest average running time.

SELECT c.category_id, AVG(f.length) AS avg_running_time
FROM film AS f
JOIN film_category AS c
ON c.film_id = f.film_id
GROUP BY c.category_id
ORDER BY avg_running_time DESC;
